@startuml

folder global.namespace.fun-io {
    [fun-io-api] <|--- [fun-io-bios]
    [fun-io-api] <|-- [fun-io-commons-compress]
    [fun-io-api] <|-- [fun-io-jackson]
    [fun-io-api] <|-- [fun-io-jaxb]
    [fun-io-api] <--- [fun-io-scala-api]
    [fun-io-api] <|-- [fun-io-xz]
}

[commons-compress] <--- [fun-io-commons-compress]
[activation-api] <--- [fun-io-jaxb]
[jackson-databind] <--- [fun-io-jackson]
[jaxb-api] <--- [fun-io-jaxb]
[jaxb-runtime] <-- [fun-io-jaxb]
[xz] <--- [fun-io-xz]

@enduml
